
const files = [
  '.editorconfig',
  '.gitignore',
  '.npmrc',
  '.stylelintrc',
  '.travis.yml',
  '.yarnrc',
  'CHANGELOG.md',
  'LICENSE.md',
  'package.json',
  'postcss.config.js',
  'README.md',
  'scripts/link-bower.js',
  'src/assets/icons/android-chrome-192x192.png',
  'src/assets/icons/android-chrome-384x384.png',
  'src/assets/icons/apple-touch-icon.png',
  'src/assets/icons/browserconfig.xml',
  'src/assets/icons/favicon-16x16.png',
  'src/assets/icons/favicon-32x32.png',
  'src/assets/icons/favicon.ico',
  'src/assets/icons/mstile-150x150.png',
  'src/assets/icons/safari-pinned-tab.svg',
  'src/assets/logo.svg',
  'src/components/containers/sk-app/index.js',
  'src/components/containers/sk-app/style.pcss',
  'src/components/containers/sk-app/template.html',
  'src/components/dumbs/sk-menu-item/index.js',
  'src/components/dumbs/sk-menu-item/style.pcss',
  'src/components/dumbs/sk-menu-item/template.html',
  'src/components/dumbs/sk-menu/index.js',
  'src/components/dumbs/sk-menu/style.pcss',
  'src/components/dumbs/sk-menu/template.html',
  'src/global-style/animations/hue-rotate.pcss',
  'src/global-style/basics/links.pcss',
  'src/global-style/basics/typography.pcss',
  'src/index.html',
  'src/index.js',
  'src/manifest.json',
  'test/suites/sk-app.html',
  'wct.conf.js',
  'webpack-module.config.js',
  'webpack-nomodule.config.js',
  'webpack.config.js'
];

module.exports = isWin => isWin ? files.map(file => file.replace(/\//g, '\\')) : files;
